version: "2.2"

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: sub-elastic
    environment:
      - cluster.name=muggle-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - subscriber-network

  kibana: 
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: sub-kibana  
    ports:
      - 5601:5601
    links:
      - elasticsearch1:elasticsearch
    networks:
      - subscriber-network

  logstash:
    image: recruit-logstash:latest
    build:
      context: .
      dockerfile: ./.docker/logstash.dockerfile
    container_name: sub-logstash  
    links:
      - elasticsearch1:elasticsearch
      - redis
    networks:
      - subscriber-network

  redis:
    image: redis:latest
    container_name: sub-redis  
    ports:
      - 6379:6379
    networks:
      - subscriber-network
 
volumes:
  esdata1:
    driver: local

networks:
  subscriber-network:
    driver: bridge
